logging:
  level:
    root: info

spring:
  datasource:
    username: postgres
    password: mysecretpassword
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          batch_versioned_data: true
          batch_size: 50
    show-sql: true
  sql:
    init:
      mode: embedded