server:
  port: 9911
  servlet:
    context-path: "/orders"
logging:
  level:
    root: info
    org:
      hibernate:
        type: trace
      springframework:
        jdbc: trace
        jdbc.datasource.init: info
        boot:
          test: debug
        test:
          context:
            jdbc: debug


spring:
  datasource:
    username: postgres
    password: mysecretpassword
    url: jdbc:postgresql://localhost:5433/postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  sql:
    init:
      mode: embedded